plugins {
    id 'java'
}

group = 'com.temporosstracker'
version = '0.1.0-SNAPSHOT'

def runeliteVersion = project.findProperty('runeliteVersion') ?: 'latest.release'

repositories {
    mavenLocal()
    maven {
        url = 'https://repo.runelite.net'
        content {
            includeGroupByRegex "net\\.runelite.*"
        }
    }
    mavenCentral()
}

dependencies {
    // Plugin compilation uses RuneLite client API, but we don't bundle it.
    compileOnly "net.runelite:client:${runeliteVersion}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(11)
}
